const http = require('http');
const fs = require('fs');
const path = require('path');
const { db, dbPath, backup, log } = require('./src/database');
const port = Number(process.env.PORT || 3020);
const publicDir = path.join(__dirname, 'public');
const types = { '.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg' };
function send(res, code, data) { res.writeHead(code, {'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}); res.end(JSON.stringify(data)); }
function read(req) { return new Promise((resolve,reject)=>{let raw='';req.on('data',x=>raw+=x);req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch(e){reject(e)}})}) }
function rows(sql, ...args){ return db.prepare(sql).all(...args); }
function one(sql, ...args){ return db.prepare(sql).get(...args); }
async function api(req,res,url){
 const p=url.pathname;
 if(req.method==='GET'&&p==='/api/health') return send(res,200,{ok:true,database:fs.existsSync(dbPath),port});
 if(req.method==='GET'&&p==='/api/dashboard') { const total=one('SELECT COUNT(*) total FROM students').total, active=one("SELECT COUNT(*) total FROM programs WHERE status='فعال'").total, waiting=one("SELECT COUNT(*) total FROM orders WHERE status LIKE 'در انتظار%'").total; return send(res,200,{stats:{total,active,waiting,movements:one('SELECT COUNT(*) total FROM movements').total},activities:rows('SELECT * FROM activity_log ORDER BY id DESC LIMIT 6'),students:rows('SELECT * FROM students ORDER BY id DESC LIMIT 5')}); }
 if(req.method==='GET'&&p==='/api/students') return send(res,200,rows('SELECT * FROM students ORDER BY id DESC'));
 if(req.method==='POST'&&p==='/api/students') { const b=await read(req); if(!b.full_name?.trim()) return send(res,400,{error:'نام شاگرد الزامی است.'}); const r=db.prepare('INSERT INTO students (full_name,mobile,goal,status,weight,height) VALUES (?,?,?,?,?,?)').run(b.full_name.trim(),b.mobile||'',b.goal||'',b.status||'فعال',Number(b.weight)||null,Number(b.height)||null); log('شاگرد جدید ثبت شد',b.full_name); return send(res,201,{id:r.lastInsertRowid}); }
 if(req.method==='GET'&&p==='/api/movements') return send(res,200,rows('SELECT * FROM movements ORDER BY id DESC'));
 if(req.method==='POST'&&p==='/api/movements') { const b=await read(req); if(!b.name?.trim()) return send(res,400,{error:'نام حرکت الزامی است.'}); const r=db.prepare('INSERT INTO movements (name,muscle_group,equipment) VALUES (?,?,?)').run(b.name.trim(),b.muscle_group||'',b.equipment||''); log('حرکت جدید ثبت شد',b.name); return send(res,201,{id:r.lastInsertRowid}); }
 if(req.method==='GET'&&p==='/api/categories') return send(res,200,rows('SELECT c.id,c.name,c.sort_order, s.id subcategory_id,s.name subcategory_name,s.sort_order subcategory_sort_order FROM exercise_categories c LEFT JOIN exercise_subcategories s ON s.category_id=c.id ORDER BY c.sort_order,s.sort_order'));
 if(req.method==='GET'&&p==='/api/exercises') { const location=url.searchParams.get('location')||'both', categoryId=url.searchParams.get('categoryId'), subCategoryId=url.searchParams.get('subCategoryId'), status=url.searchParams.get('status')||'active', query=(url.searchParams.get('query')||'').trim(); if(!categoryId) return send(res,200,[]); let sql='SELECT * FROM exercises WHERE category_id=? AND status=?', params=[categoryId,status]; if(location!=='both'){sql+=' AND (location=? OR location=\'both\')';params.push(location)} if(subCategoryId&&subCategoryId!=='all'){sql+=' AND subcategory_id=?';params.push(subCategoryId)} if(query){sql+=' AND name_fa LIKE ?';params.push(`%${query}%`)} sql+=' ORDER BY id ASC'; return send(res,200,rows(sql,...params)); }
 if(req.method==='POST'&&p==='/api/exercises') { const b=await read(req); if(!b.name_fa?.trim()||!b.category_id) return send(res,400,{error:'نام، دسته و زیردسته حرکت را وارد کنید.'}); const r=db.prepare('INSERT INTO exercises (name_fa,location,category_id,subcategory_id,status) VALUES (?,?,?,?,?)').run(b.name_fa.trim(),b.location||'both',b.category_id,b.subcategory_id||null,b.status==='archived'?'archived':'active'); log('حرکت جدید ثبت شد',b.name_fa); return send(res,201,{id:Number(r.lastInsertRowid)}); }
 const exerciseMatch=p.match(/^\/api\/exercises\/(\d+)$/);
 if(req.method==='PUT'&&exerciseMatch) { const b=await read(req), id=Number(exerciseMatch[1]); if(!b.name_fa?.trim()||!b.category_id) return send(res,400,{error:'نام و دسته حرکت الزامی است.'}); const r=db.prepare('UPDATE exercises SET name_fa=?,location=?,category_id=?,subcategory_id=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(b.name_fa.trim(),b.location||'both',b.category_id,b.subcategory_id||null,b.status==='archived'?'archived':'active',id); if(!r.changes)return send(res,404,{error:'حرکت پیدا نشد.'}); log('حرکت ویرایش شد',b.name_fa);return send(res,200,{id}); }
 const bulkAction={ '/api/exercises/bulk-archive':'archived','/api/exercises/bulk-restore':'active' }[p];
 if(req.method==='POST'&&bulkAction){const b=await read(req),ids=Array.isArray(b.ids)?b.ids.map(Number).filter(Number.isInteger):[];if(!ids.length)return send(res,400,{error:'حداقل یک حرکت انتخاب کنید.'});const marks=ids.map(()=>'?').join(',');db.prepare(`UPDATE exercises SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id IN (${marks})`).run(bulkAction,...ids);log(bulkAction==='active'?'حرکات بازیابی شدند':'حرکات آرشیو شدند',`${ids.length} حرکت`);return send(res,200,{count:ids.length});}
 if(req.method==='DELETE'&&p==='/api/exercises/bulk-delete'){const b=await read(req),ids=Array.isArray(b.ids)?b.ids.map(Number).filter(Number.isInteger):[];if(!ids.length)return send(res,400,{error:'حداقل یک حرکت انتخاب کنید.'});const marks=ids.map(()=>'?').join(',');db.prepare(`DELETE FROM exercises WHERE id IN (${marks})`).run(...ids);log('حرکات حذف شدند',`${ids.length} حرکت`);return send(res,200,{count:ids.length});}
 if(req.method==='GET'&&p==='/api/programs') return send(res,200,rows('SELECT p.*,s.full_name student_name FROM programs p LEFT JOIN students s ON s.id=p.student_id ORDER BY p.id DESC'));
 if(req.method==='POST'&&p==='/api/programs') { const b=await read(req); if(!b.title?.trim()||!b.type) return send(res,400,{error:'عنوان و نوع برنامه الزامی هستند.'}); const r=db.prepare('INSERT INTO programs (student_id,title,type,status,start_date,end_date,notes) VALUES (?,?,?,?,?,?,?)').run(b.student_id||null,b.title.trim(),b.type,b.status||'پیش‌نویس',b.start_date||null,b.end_date||null,b.notes||''); log('برنامه جدید ثبت شد',b.title); return send(res,201,{id:r.lastInsertRowid}); }
 if(req.method==='POST'&&p==='/api/backup') { const file=backup(); log('نسخه پشتیبان ساخته شد',file); return send(res,201,{file}); }
 return send(res,404,{error:'مسیر API پیدا نشد.'});
}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host}`);try{if(url.pathname.startsWith('/api/')) return await api(req,res,url); const wanted=url.pathname==='/'?'/index.html':url.pathname;const file=path.normalize(path.join(publicDir,wanted));if(file.startsWith(publicDir)&&fs.existsSync(file)&&fs.statSync(file).isFile()){res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream','Cache-Control':'no-store'});return fs.createReadStream(file).pipe(res)}res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});fs.createReadStream(path.join(publicDir,'index.html')).pipe(res)}catch(error){console.error(error);send(res,500,{error:'خطای داخلی سرور',detail:error.message})}});
server.listen(port,'0.0.0.0',()=>console.log(`Yasnafit is running at http://localhost:${port}`));
