'use strict';
const crypto=require('crypto');
const BLOCKED=/token|secret|password|session|cookie|storage_path|file_path|hash/i;
function uuid(){return crypto.randomUUID?crypto.randomUUID():crypto.randomBytes(16).toString('hex');}
function safeMetadata(input,depth=0){if(depth>3)return null;if(input===null||['string','number','boolean'].includes(typeof input))return typeof input==='string'?input.slice(0,500):input;if(Array.isArray(input))return input.slice(0,30).map(item=>safeMetadata(item,depth+1));if(typeof input==='object'){const output={};for(const [key,value] of Object.entries(input)){if(BLOCKED.test(key))continue;output[key]=safeMetadata(value,depth+1);}return output;}return String(input).slice(0,500);}
function record(db,{actorType='system',actorId=null,action,entityType,entityId=null,entityStableId=null,metadata={}}){if(!['coach','student','system'].includes(actorType))throw new Error('Invalid audit actor');if(!action||!entityType)throw new Error('Audit action and entity are required');try{return db.prepare('INSERT INTO audit_events(stable_id,actor_type,actor_id,action,entity_type,entity_id,entity_stable_id,metadata_json) VALUES(?,?,?,?,?,?,?,?)').run(uuid(),actorType,actorId,String(action).slice(0,100),String(entityType).slice(0,80),entityId,entityStableId,JSON.stringify(safeMetadata(metadata))).lastInsertRowid;}catch(error){console.error('[Audit]',error.message);return null;}}
function listForEntity(db,entityType,entityId,limit=100){return db.prepare('SELECT stable_id,actor_type,actor_id,action,entity_type,entity_id,entity_stable_id,metadata_json,created_at FROM audit_events WHERE entity_type=? AND entity_id=? ORDER BY id DESC LIMIT ?').all(entityType,entityId,Math.min(500,Math.max(1,limit))).map(row=>({...row,metadata:JSON.parse(row.metadata_json||'{}'),metadata_json:undefined}));}
function listForStudent(db,studentId,limit=200){return db.prepare("SELECT stable_id,actor_type,actor_id,action,entity_type,entity_id,entity_stable_id,metadata_json,created_at FROM audit_events WHERE (actor_type='student' AND actor_id=?) OR (json_extract(metadata_json,'$.student_id')=?) ORDER BY id DESC LIMIT ?").all(studentId,studentId,Math.min(500,limit)).map(row=>({...row,metadata:JSON.parse(row.metadata_json||'{}'),metadata_json:undefined}));}
module.exports={record,listForEntity,listForStudent,safeMetadata};
