'use strict';
const crypto=require('crypto');
function uuid(){return crypto.randomUUID?crypto.randomUUID():crypto.randomBytes(16).toString('hex');}
function cleanText(value,max=2000){const text=String(value??'').trim();if(text.length>max)throw new Error('متن بیش از حد طولانی است');return text;}
function notify(db,{audienceType,studentId=null,type,title,body='',entityType=null,entityId=null}){if(!['coach','student'].includes(audienceType))throw new Error('Invalid notification audience');return db.prepare('INSERT INTO notifications(stable_id,audience_type,student_id,type,title,body,entity_type,entity_id) VALUES(?,?,?,?,?,?,?,?)').run(uuid(),audienceType,studentId,String(type).slice(0,80),cleanText(title,200),cleanText(body,1000),entityType,entityId).lastInsertRowid;}
function listNotifications(db,audienceType,studentId=null,limit=50){const rows=audienceType==='student'?db.prepare("SELECT stable_id,type,title,body,entity_type,entity_id,read_at,created_at FROM notifications WHERE audience_type='student' AND student_id=? AND deleted_at IS NULL ORDER BY id DESC LIMIT ?").all(studentId,limit):db.prepare("SELECT n.stable_id,n.type,n.title,n.body,n.entity_type,n.entity_id,n.read_at,n.created_at,n.student_id,s.full_name student_name,s.case_number student_case_number FROM notifications n LEFT JOIN students s ON s.id=n.student_id WHERE n.audience_type='coach' AND n.deleted_at IS NULL ORDER BY n.id DESC LIMIT ?").all(limit);return rows;}
function markNotificationRead(db,stableId,audienceType,studentId=null){const result=audienceType==='student'?db.prepare("UPDATE notifications SET read_at=COALESCE(read_at,CURRENT_TIMESTAMP) WHERE stable_id=? AND audience_type='student' AND student_id=? AND deleted_at IS NULL").run(stableId,studentId):db.prepare("UPDATE notifications SET read_at=COALESCE(read_at,CURRENT_TIMESTAMP) WHERE stable_id=? AND audience_type='coach' AND deleted_at IS NULL").run(stableId);return result.changes>0;}
function conversation(db,studentId){let row=db.prepare('SELECT * FROM conversations WHERE student_id=? AND deleted_at IS NULL').get(studentId);if(!row){const stable=uuid(),result=db.prepare('INSERT INTO conversations(stable_id,student_id) VALUES(?,?)').run(stable,studentId);row=db.prepare('SELECT * FROM conversations WHERE id=?').get(result.lastInsertRowid);}return row;}
function listMessages(db,studentId,readerType){const convo=conversation(db,studentId);db.prepare(`UPDATE messages SET read_at=COALESCE(read_at,CURRENT_TIMESTAMP) WHERE conversation_id=? AND sender_type<>? AND deleted_at IS NULL`).run(convo.id,readerType);return db.prepare('SELECT stable_id,sender_type,body,read_at,created_at FROM messages WHERE conversation_id=? AND deleted_at IS NULL ORDER BY id ASC LIMIT 500').all(convo.id);}
function sendMessage(db,studentId,senderType,body){if(!['coach','student'].includes(senderType))throw new Error('Invalid sender');const text=cleanText(body,2000);if(!text)throw new Error('متن پیام الزامی است');const convo=conversation(db,studentId),stable=uuid();db.prepare('INSERT INTO messages(stable_id,conversation_id,sender_type,sender_student_id,body) VALUES(?,?,?,?,?)').run(stable,convo.id,senderType,senderType==='student'?studentId:null,text);db.prepare('UPDATE conversations SET updated_at=CURRENT_TIMESTAMP WHERE id=?').run(convo.id);return {stable_id:stable,sender_type:senderType,body:text,created_at:new Date().toISOString()};}
function activeProgram(db,studentId){return db.prepare("SELECT * FROM training_programs WHERE student_id=? AND status='ACTIVE' AND deleted_at IS NULL ORDER BY program_number DESC,id DESC LIMIT 1").get(studentId);}
function startWorkout(db,studentId,dayRef,notes=''){const program=activeProgram(db,studentId);if(!program)throw new Error('برنامه فعال پیدا نشد');const day=db.prepare('SELECT * FROM program_days WHERE stable_id=? AND program_id=? AND deleted_at IS NULL').get(dayRef,program.id);if(!day)throw new Error('روز تمرینی معتبر نیست');const stable=uuid(),result=db.prepare('INSERT INTO workout_sessions(stable_id,student_id,program_id,program_day_id,notes) VALUES(?,?,?,?,?)').run(stable,studentId,program.id,day.id,cleanText(notes,2000));return db.prepare('SELECT stable_id,status,started_at,notes FROM workout_sessions WHERE id=?').get(result.lastInsertRowid);}
function saveWorkoutResults(db,studentId,sessionRef,results){if(!Array.isArray(results)||results.length>200)throw new Error('نتایج تمرین نامعتبر است');const session=db.prepare("SELECT * FROM workout_sessions WHERE stable_id=? AND student_id=? AND status='IN_PROGRESS' AND deleted_at IS NULL").get(sessionRef,studentId);if(!session)throw new Error('جلسه تمرین قابل ویرایش نیست');db.exec('BEGIN');try{const upsert=db.prepare(`INSERT INTO workout_results(stable_id,workout_session_id,prescribed_set_id,actual_repetitions,actual_weight,actual_duration_seconds,status,notes) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(workout_session_id,prescribed_set_id) DO UPDATE SET actual_repetitions=excluded.actual_repetitions,actual_weight=excluded.actual_weight,actual_duration_seconds=excluded.actual_duration_seconds,status=excluded.status,notes=excluded.notes,updated_at=CURRENT_TIMESTAMP`);for(const item of results){const prescribed=db.prepare(`SELECT ms.id FROM movement_sets ms JOIN program_movements pm ON pm.id=ms.movement_id JOIN exercise_systems es ON es.id=pm.system_id JOIN program_days pd ON pd.id=es.day_id WHERE ms.stable_id=? AND pd.id=? AND pd.program_id=? AND ms.deleted_at IS NULL`).get(item.set_ref,session.program_day_id,session.program_id);if(!prescribed)throw new Error('ست تجویزی معتبر نیست');const weight=item.actual_weight===null||item.actual_weight===''?null:Number(item.actual_weight),duration=item.actual_duration_seconds===null||item.actual_duration_seconds===''?null:Number(item.actual_duration_seconds);if(weight!==null&&(!Number.isFinite(weight)||weight<0||weight>1000))throw new Error('وزن اجراشده نامعتبر است');if(duration!==null&&(!Number.isInteger(duration)||duration<0||duration>86400))throw new Error('زمان اجرا نامعتبر است');if(!['COMPLETED','SKIPPED'].includes(item.status))throw new Error('وضعیت ست نامعتبر است');upsert.run(uuid(),session.id,prescribed.id,cleanText(item.actual_repetitions,30),weight,duration,item.status,cleanText(item.notes,500));}db.prepare('UPDATE workout_sessions SET updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=?').run(session.id);db.exec('COMMIT');}catch(error){db.exec('ROLLBACK');throw error;}return workoutSession(db,studentId,sessionRef);}
function completeWorkout(db,studentId,sessionRef,{status='COMPLETED',notes=''}={}){if(!['COMPLETED','SKIPPED'].includes(status))throw new Error('وضعیت جلسه نامعتبر است');const result=db.prepare("UPDATE workout_sessions SET status=?,notes=?,completed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE stable_id=? AND student_id=? AND status='IN_PROGRESS' AND deleted_at IS NULL").run(status,cleanText(notes,2000),sessionRef,studentId);if(!result.changes)throw new Error('جلسه تمرین قابل تکمیل نیست');return workoutSession(db,studentId,sessionRef);}
function workoutSession(db,studentId,sessionRef){const session=db.prepare('SELECT ws.stable_id,ws.status,ws.started_at,ws.completed_at,ws.notes,pd.day_number,tp.title program_title FROM workout_sessions ws JOIN program_days pd ON pd.id=ws.program_day_id JOIN training_programs tp ON tp.id=ws.program_id WHERE ws.stable_id=? AND ws.student_id=? AND ws.deleted_at IS NULL').get(sessionRef,studentId);if(!session)return null;session.results=db.prepare('SELECT wr.stable_id,ms.stable_id set_ref,wr.actual_repetitions,wr.actual_weight,wr.actual_duration_seconds,wr.status,wr.notes,wr.created_at FROM workout_results wr JOIN movement_sets ms ON ms.id=wr.prescribed_set_id WHERE wr.workout_session_id=(SELECT id FROM workout_sessions WHERE stable_id=?) AND wr.deleted_at IS NULL ORDER BY wr.id').all(sessionRef);return session;}
function listWorkouts(db,studentId,limit=100){return db.prepare('SELECT ws.stable_id,ws.status,ws.started_at,ws.completed_at,ws.notes,pd.day_number,tp.title program_title,(SELECT COUNT(*) FROM workout_results wr WHERE wr.workout_session_id=ws.id AND wr.status=\'COMPLETED\' AND wr.deleted_at IS NULL) completed_sets FROM workout_sessions ws JOIN program_days pd ON pd.id=ws.program_day_id JOIN training_programs tp ON tp.id=ws.program_id WHERE ws.student_id=? AND ws.deleted_at IS NULL ORDER BY ws.id DESC LIMIT ?').all(studentId,limit);}
function performance(db,studentId){const counts=db.prepare("SELECT COUNT(*) total,SUM(status='COMPLETED') completed,SUM(status='SKIPPED') skipped,MAX(COALESCE(completed_at,started_at)) last_workout FROM workout_sessions WHERE student_id=? AND deleted_at IS NULL").get(studentId);const decided=Number(counts.completed||0)+Number(counts.skipped||0);return {sessions_total:Number(counts.total||0),sessions_completed:Number(counts.completed||0),sessions_skipped:Number(counts.skipped||0),completion_rate:decided?Math.round(Number(counts.completed||0)/decided*100):null,last_workout:counts.last_workout,workouts:listWorkouts(db,studentId,20)};}
function ensureProgramEndReminder(db,studentId){const program=activeProgram(db,studentId);if(!program?.end_date)return;const days=Math.ceil((new Date(`${program.end_date}T23:59:59`).getTime()-Date.now())/86400000);if(days<0||days>7)return;for(const audienceType of ['student','coach']){const exists=db.prepare("SELECT 1 FROM notifications WHERE audience_type=? AND student_id=? AND type='program_ending' AND entity_type='training_program' AND entity_id=? AND deleted_at IS NULL").get(audienceType,studentId,program.id);if(!exists)notify(db,{audienceType,studentId,type:'program_ending',title:'پایان برنامه نزدیک است',body:`${days} روز تا پایان ${program.title}`,entityType:'training_program',entityId:program.id});}}
module.exports={notify,listNotifications,markNotificationRead,conversation,listMessages,sendMessage,startWorkout,saveWorkoutResults,completeWorkout,workoutSession,listWorkouts,performance,ensureProgramEndReminder};
